# Generated by Django 5.1.4 on 2025-01-17 14:30

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="original",
            field=models.CharField(
                blank=True, help_text="Original file name.", max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                storage=django_minio_backend.models.MinioBackend(bucket_name="main"),
                upload_to="original_files/",
            ),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="file",
            field=models.FileField(
                storage=django_minio_backend.models.MinioBackend(bucket_name="main"),
                upload_to="version_files/",
            ),
        ),
    ]
