# Generated by Django 5.1.4 on 2025-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_file_original_alter_file_file_alter_fileversion_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="original",
        ),
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title of the file. By default is original file name.",
                max_length=256,
                null=True,
            ),
        ),
    ]
