# Generated by Django 3.2 on 2021-05-30 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, unique=True)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Url without domain. You can find domain in site.url .', max_length=512, unique=True)),
                ('last_visit', models.DateTimeField(help_text='When spider was on the page in last time.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.site')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(help_text='ID or Slug.', max_length=256)),
                ('last_updated', models.DateTimeField(help_text='Datetime from ArticleSnapshot.timestamp')),
                ('title', models.CharField(blank=True, default='', help_text='Title.', max_length=256)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Desc  that was scriped from page.')),
                ('publish_date', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.site')),
            ],
            options={
                'unique_together': {('site', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='ArticleSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Datetime when data was read from page.')),
                ('title', models.CharField(blank=True, default='', help_text='Title.', max_length=256)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Desc  that was scriped from page.')),
                ('publish_date', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.article')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.page')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.session')),
            ],
            options={
                'unique_together': {('session', 'page', 'article')},
            },
        ),
    ]
