# Generated by Django 3.2 on 2021-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_article_articlesnapshot_page_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='load_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='load_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Main text of article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(help_text='Title.'),
        ),
    ]
