# Generated by Django 3.2 on 2021-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0003_auto_20210604_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesnapshot',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
