# Generated by Django 3.2 on 2021-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0004_alter_articlesnapshot_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesnapshot',
            name='body',
            field=models.JSONField(default=dict, help_text='Desc  that was scriped from page.'),
        ),
    ]
