# Generated by Django 5.1.4 on 2024-12-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='org.org'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgusergroup',
            name='org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_user_groups', to='org.org'),
        ),
    ]
